### ISSUE TITLE
[Bug]: Typing "0" in the Section column for a Party Cooldown crashes the plugin

### ISSUE THREAD

**Issue by Ishamyyl** [DelvUI/DelvUI#1000]
### What are you trying to do?

1. Open DelvUI Settings
2. Party Cooldowns tab > Cooldowns Tracked tab
3. Find any ability and swap to a class that has that ability
4. Double-click the "Section" column for manual editing
5. Type `0`
6. Notice the plugin crashes

I was able to reproduce this issue from the steps above on v1.0.0.3

### What is the expected behavior?

The plugin warns that `0` is an invalid input or to automatically correct itself to `1`.

### What actually happened?

The plugin crashed

### Suggested solution

To fix: 
1. Exit the game
2. Open `%AppData%\XIVLauncher\pluginConfigs\DelvUI\Party Cooldowns\Cooldowns Tracked.json` for editing
4. Find `"Column": 0` and change it to `"Column": 1`
5. Save the file
6. Relaunch the game

Not a huge deal since most users probably use the slider, but mistakes happen and it can be a pain to correct.
Just need to not let that slider be editable, or any other standard mitigation techniques.

### Logs

```shell
2022-01-27 12:53:41.220 -06:00 [ERR] [DelvUI] UiBuilder OnBuildUi caught exception
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at DelvUI.Interface.PartyCooldowns.PartyCooldownsHud.UpdateCooldowns() in D:\Projects\delvui\DelvUI\Interface\PartyCooldowns\PartyCooldownsHud.cs:line 77
   at DelvUI.Interface.PartyCooldowns.PartyCooldownsManager.OnMembersChanged(PartyManager sender) in D:\Projects\delvui\DelvUI\Interface\PartyCooldowns\PartyCooldownsManager.cs:line 204
   at DelvUI.Plugin.UpdateJob() in D:\Projects\delvui\DelvUI\Plugin.cs:line 262
   at DelvUI.Plugin.Draw() in D:\Projects\delvui\DelvUI\Plugin.cs:line 266
   at Dalamud.Interface.UiBuilder.OnDraw() in C:\goatsoft\companysecrets\dalamud\Interface\UiBuilder.cs:line 287
2022-01-27 12:53:41.250 -06:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wMS0yN1QxMjo1Mzo0MS4yNDcyMTkzLTA2OjAwIiwiSW5mbyI6IlN5c3RlbS5Bcmd1bWVudE91dE9mUmFuZ2VFeGNlcHRpb246IEluZGV4IHdhcyBvdXQgb2YgcmFuZ2UuIE11c3QgYmUgbm9uLW5lZ2F0aXZlIGFuZCBsZXNzIHRoYW4gdGhlIHNpemUgb2YgdGhlIGNvbGxlY3Rpb24uIChQYXJhbWV0ZXIgJ2luZGV4JylcclxuICAgYXQgRGVsdlVJLkludGVyZmFjZS5QYXJ0eUNvb2xkb3ducy5QYXJ0eUNvb2xkb3duc0h1ZC5VcGRhdGVDb29sZG93bnMoKSBpbiBEOlxcUHJvamVjdHNcXGRlbHZ1aVxcRGVsdlVJXFxJbnRlcmZhY2VcXFBhcnR5Q29vbGRvd25zXFxQYXJ0eUNvb2xkb3duc0h1ZC5jczpsaW5lIDc3XHJcbiAgIGF0IERlbHZVSS5JbnRlcmZhY2UuUGFydHlDb29sZG93bnMuUGFydHlDb29sZG93bnNNYW5hZ2VyLk9uTWVtYmVyc0NoYW5nZWQoUGFydHlNYW5hZ2VyIHNlbmRlcikgaW4gRDpcXFByb2plY3RzXFxkZWx2dWlcXERlbHZVSVxcSW50ZXJmYWNlXFxQYXJ0eUNvb2xkb3duc1xcUGFydHlDb29sZG93bnNNYW5hZ2VyLmNzOmxpbmUgMjA0XHJcbiAgIGF0IERlbHZVSS5QbHVnaW4uVXBkYXRlSm9iKCkgaW4gRDpcXFByb2plY3RzXFxkZWx2dWlcXERlbHZVSVxcUGx1Z2luLmNzOmxpbmUgMjYyXHJcbiAgIGF0IERlbHZVSS5QbHVnaW4uRHJhdygpIGluIEQ6XFxQcm9qZWN0c1xcZGVsdnVpXFxEZWx2VUlcXFBsdWdpbi5jczpsaW5lIDI2NlxyXG4gICBhdCBEYWxhbXVkLkludGVyZmFjZS5VaUJ1aWxkZXIuT25EcmF3KCkgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcSW50ZXJmYWNlXFxVaUJ1aWxkZXIuY3M6bGluZSAyODciLCJDb250ZXh0IjoiW1wiRGVsdlVJXCJdIFVpQnVpbGRlciBPbkJ1aWxkVWkgY2F1Z2h0IGV4Y2VwdGlvbiJ9
```

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Ishamyyl** [comment]
Confirmed resolved in v1.0.1.0, the slider is no longer manually editable.

Quick work! Yall awesome, thanks so much!
